### PR TITLE
Adding appimage build script

### PR DESCRIPTION
**Pull request by azubieta**
W I P
Use the script inside travis-ci. It was test locally. Right now it build the release 0.9.15-beta_amd64.deb

Is there a way of specifying inside travis the path to the latest generated deb file?

### CODE REVIEW

**Comment by limpkin** [comment]
@raoulh are you available 16h our time to talk with @azubieta regarding some questions he has?

**Comment by azubieta** [comment]
@raoulh I will need your help on integrating the appimage script into travis.
Actually I don't need the deb file just the linux binaries, so what we need to do is:
- trigger the script after a release build is complete
- make the binaries available to the script code
- push the generated AppImage file to github

**Comment by raoulh** [comment]
Hi,

 - Put the call to `appimage.sh` in `scripts/ci/linux/after_success.sh` at the end, after the deb is built
 - The binaries are built inside docker. So you need to call the `appimage.sh` script from within docker. See [$DOCKER_EXEC](https://github.com/mooltipass/moolticute/blob/master/scripts/ci/linux/after_success.sh#L76)
 - For the deb it's done here: https://github.com/mooltipass/moolticute/blob/master/scripts/ci/linux/after_success.sh#L79

**Comment by limpkin** [comment]
👍

**Comment by azubieta** [comment]
@raoulh I'm not quite handy with docker, can I run my whole script inside docker ? How it would be

**Comment by raoulh** [comment]
Just run your script with
```
$DOCKER_EXEC your_script_or_command
```
The linux binaries are here `build-linux/moolticuted` and `build-linux/moolticute`

**Comment by azubieta** [comment]
I'll at freenode  #mooltipass for debugging.

**Comment by azubieta** [comment]
This is a mess. Rewriting history and making a new PR.

**Pull request closed without merging**
