### PR TITLE
#257 add setting for systray icon

### LINKED ISSUE #257: White systray icon
I would appreciate to have a white systray icon for my dark menu bar. Especially for Gnome desktop manager.

### PR DESCRIPTION
**Pull request by araab**
fix #257

### CODE REVIEW

**Comment by limpkin** [comment]
@raoulh can you review and merge?

**Comment by raoulh** [comment]
Not good for me. Default value is not set depending on the OS, all #ifdef are removed

**Comment by limpkin** [comment]
@araab : are you planning to modify your PR according to @raoulh  's review? otherwise one of our devs will do it.

**Comment by raoulh** [comment]
@araab Why did you close this PR? You may just update your PR by adding the #ifdef again for all OSes to set their default values. Then we can merge that.
thanks

**Comment by araab** [comment]
I don't have time to change it. So if you want you can change it.

**Pull request closed without merging**
