### PR TITLE
[BLE] Add TOTP Credential support

### PR DESCRIPTION
**Pull request by deXol**
- Added TOTP Credential dialog in MMM

kép

- Added CyoEncode lib for Base32 encode/decode

**Credential with TOTP:**
kép
View TOTP Credential button and a clock icon next to edit icon are displayed

**Credential without TOTP:**
kép

### CODE REVIEW

**Comment by limpkin** [comment]
stupid thing: can you align the left of the bottom with the left of the drop down lists?

**Comment by limpkin** [comment]
also, can you send UTC time to the device now? :)

**Comment by limpkin** [comment]
awesome work, as always! quick question: did you check that you could import / export databases with TOTP creds?

**Comment by deXol** [comment]
> 
> 
> stupid thing: can you align the left of the bottom with the left of the drop down lists?

I can do something like that:
kép

But if I edit the credential it still looks weird:
kép

**Comment by limpkin** [comment]
actually maybe center it in the middle of the input fields instead?

**Comment by limpkin** [comment]
with the discard changes / confirm changes below

**Pull request merged**
