### PR TITLE
291 app image cant create desktop file for system integration

### PR DESCRIPTION
**Pull request by asashnov**
Extra "mkdir" won't break anything.
I just need to make sure I didn't break the build process itself (let's see what CI says)

### CODE REVIEW

**Comment by asashnov** [comment]
Also, changed 'return 0'  to 'exit 0' as bash produces a warning:
https://api.travis-ci.org/v3/job/395056809/log.txt  (at the end)

**Comment by asashnov** [comment]
I managed to test  scripts/ci/linux on my machine with Docker, and found the error:

```
+ patch -p0 ./usr/bin/moolticute.sh.wrapper
scripts/ci/linux/appimage.sh: line 127: moolticute.sh.wrapper.patch: No such file or directory

```
so need to fix it and test more

**Comment by limpkin** [comment]
@raoulh what's the status of this PR?

**Comment by asashnov** [comment]
AppImage creation was remake using actual recommendations

**Pull request closed without merging**
