### PR TITLE
Transform to lower case all service names before they are sent to the device.

### PR DESCRIPTION
**Pull request by azubieta**
Implements #165

### CODE REVIEW

**Comment by limpkin** [comment]
@raoulh did you review that?

**Comment by limpkin** [comment]
can we merge that one and write in our todo list to implement it in the daemon as well? :)

**Comment by limpkin** [comment]
ping @raoulh

**Comment by raoulh** [comment]
This PR is wrong, i pushed a correct fix for this problem in master

**Comment by limpkin** [comment]
@raoulh are you sure? 
Consider the following scenario:
- service "foo" is in the device
- in MMM, user wants to add "Foo"

what will then happen?

**Comment by raoulh** [comment]
I already pushed a better fix for all those cases in master

**Comment by limpkin** [comment]
yep, I know that :).
But in your better fix, is the scenario described above correctly handled?

**Comment by raoulh** [comment]
Of course.

**Comment by limpkin** [comment]
awesome :D

**Pull request closed without merging**
