### PR TITLE
#247 Develop247 device settings read fix

### PR DESCRIPTION
**Pull request by deXol**
If autolaunch was enabled, then after OS start, the settings from the device were not loaded.
This was because in that case mainwindow wasn't created during startup, so when the daemon sent the parameter loaded signals, then the mainwindow could not process them.

### CODE REVIEW

**Comment by limpkin** [comment]
woohoo! very nice

**Comment by raoulh** [comment]
Does it work on macOS? At startup on macOS it crashed when creating the main window too early with start at boot is enabled.

**Comment by deXol** [comment]
> Does it work on macOS? At startup on macOS it crashed when creating the main window too early with start at boot is enabled.

Checked on Mac (only debug version, was not able to build release), it does not crash, works as before, but with the correct settings read.

**Comment by limpkin** [comment]
i guess we can merge and beta release and double check?

**Comment by raoulh** [comment]
Ok, let's try with a test release build

**Pull request merged**
