### PR TITLE
Start working on doc for udev rule on non systemd linux

### PR DESCRIPTION
**Pull request by bobsaintcool**
see[0].

[0] https://github.com/mooltipass/mooltipass-udev/pull/3#issuecomment-1329915978

### CODE REVIEW

**Comment by bobsaintcool** [comment]
Not tested, just inspiration for https://github.com/mooltipass/mooltipass-udev/pull/3#issuecomment-1329915978

**Comment by limpkin** [comment]
I'm OK to merge this as it is... simply give me the go ahead :)

**Comment by bobsaintcool** [comment]
Thanks, i'll wait until the weekend hopefully @PoroCYon can provide feedback as I don't have the environment to test

**Comment by PoroCYon** [comment]
It looks fine to me, though I'd change the wording/fix the spelling a bit:

```md
Note: For Linux systems without systemd (eg. Gentoo, Void Linux), please refer to [this section](#non-systemd-linux).
```

```md
##### Linux without systemd

The main [udev rules](https://aur.archlinux.org/packages/mooltipass-udev/)
rely on integration between systemd, systemd-login and systemd-udevd
to automatically allow any user logged in to access mooltipass devices.
This will not works on devices without systemd, one
workaround is to change the `TAG+="uaccess"` to
`GROUP="plugdev"` and add your interactive user to this group.

See [this issue](https://github.com/mooltipass/mooltipass-udev/pull/3) for more information and a possible patch.
```

(I wouldn't refer to my packages here, as those are specific to Void Linux, and also don't yet exist fully.)

**Comment by bobsaintcool** [comment]
Thanks for you review.

@limpkin I believe we are good to go on my side

**Comment by limpkin** [comment]
thanks everyone :)

**Pull request merged**
